// File generated by FlutterFire CLI.
// See https://firebase.flutter.dev/docs/cli
//
// IMPORTANT: Replace the placeholder values below with the real values from
// your Firebase project console at https://console.firebase.google.com
// Project: rafiqfamily-5c8ed
// Go to: Project Settings → Your Apps → Web App → SDK Setup and Configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return web;
    }
  }

  // ─── Web ────────────────────────────────────────────────────────────────
  // TODO: Replace all placeholder values with real values from Firebase Console
  // Project: rafiqfamily-5c8ed  → Settings → Web App → Config

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7zdhLkt6VA1SGD8qTUPKqkZleJqvLheA',
    appId: '1:684066491065:web:4d1a895858361fcef3e968',
    messagingSenderId: '684066491065',
    projectId: 'rafiqfamily-5c8ed',
    authDomain: 'rafiqfamily-5c8ed.firebaseapp.com',
    storageBucket: 'rafiqfamily-5c8ed.firebasestorage.app',
    measurementId: 'G-RF4R6KWJRJ',
  );
  // ─── Android ────────────────────────────────────────────────────────────
  // TODO: Replace with values from google-services.json

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7GKu5fhm1uN-3NiOmHbDbGU2FUr_L0Bk',
    appId: '1:684066491065:android:3188175f018a592af3e968',
    messagingSenderId: '684066491065',
    projectId: 'rafiqfamily-5c8ed',
    storageBucket: 'rafiqfamily-5c8ed.firebasestorage.app',
  );
  // ─── iOS ────────────────────────────────────────────────────────────────
  // TODO: Replace with values from GoogleService-Info.plist

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqQoeou5RHHUN01v4nprJeGtY6v1kuolI',
    appId: '1:684066491065:ios:41d66ca9a54ae6a3f3e968',
    messagingSenderId: '684066491065',
    projectId: 'rafiqfamily-5c8ed',
    storageBucket: 'rafiqfamily-5c8ed.firebasestorage.app',
    iosBundleId: 'com.dailyislamicwidget.dailyIslamicWidget',
  );
  // ─── macOS ──────────────────────────────────────────────────────────────
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_MACOS_API_KEY',
    appId: 'REPLACE_WITH_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'rafiqfamily-5c8ed',
    storageBucket: 'rafiqfamily-5c8ed.firebasestorage.app',
    iosBundleId: 'com.dailyislamicwidget.app',
  );
}
